/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_musicgenerator_free(a: number, b: number): void;
export function main(): void;
export function musicgenerator_is_playing(a: number): number;
export function musicgenerator_new(): number;
export function musicgenerator_schedule_more_notes(a: number): void;
export function musicgenerator_start(a: number): void;
export function musicgenerator_stop(a: number): void;
export function __wbg_neommathgame_free(a: number, b: number): void;
export function neommathgame_check_answer(a: number, b: number): number;
export function neommathgame_generate_question(a: number): Array;
export function neommathgame_get_accuracy(a: number): number;
export function neommathgame_get_difficulty(a: number): number;
export function neommathgame_get_high_score(a: number): number;
export function neommathgame_get_mascot_message(a: number, b: number, c: number, d: number, e: number): Array;
export function neommathgame_get_score(a: number): number;
export function neommathgame_get_time_left(a: number): number;
export function neommathgame_get_ui_text(a: number, b: number, c: number): Array;
export function neommathgame_is_music_playing(a: number): number;
export function neommathgame_load_locales(a: number, b: number, c: number): void;
export function neommathgame_new(): number;
export function neommathgame_reset_game(a: number): void;
export function neommathgame_speak_mascot_message(a: number, b: number, c: number, d: number, e: number): void;
export function neommathgame_start_music(a: number): void;
export function neommathgame_stop_music(a: number): void;
export function neommathgame_tick(a: number): number;
export function neommathgame_toggle_audio(a: number): number;
export function __wbg_audiomanager_free(a: number, b: number): void;
export function audiomanager_new(): number;
export function audiomanager_speak(a: number, b: number, c: number): void;
export function audiomanager_speak_with_pitch(a: number, b: number, c: number, d: number): void;
export function audiomanager_toggle(a: number): number;
export function __wbg_localizationmanager_free(a: number, b: number): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_exn_store(a: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
